name: DVC Pull

on:
  push:
    branches:
      - main

jobs:
  pull-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install DVC and dependencies
        run: |
          pip install dvc[azure]
      - name: Pull data from DVC
        run: |
          dvc pull
      - name: Verify DVC Data
        run: |
          dvc status